### ISSUE TITLE
unexpected results using an exclusion pattern

### ISSUE THREAD

**Issue by brewster1134** [thecotne/webpack-glob-entry#105]
i currently have a directory with the following files:

```js
console.ts
console.sass
console.test.ts
core.ts
core.test.ts
handler.ts
package.json
README.md
service.ts
```

---
when i use normal pattern... `./*.ts`

```js
console.log(entry('./*.ts'))
{
  console: './console.test.ts',
  core: './core.test.ts',
  handler: './handler.ts',
  service: './service.ts'
}
```
which is not what i want, since i want to exclude the `.test.ts` files

---
so when i use an exclusion pattern... `./*[!.test].ts`

```js
console.log(entry('./*[!.test].ts'))
{
  handler: './handler.ts'
}
```
which makes no sense to me.

---
so then i try add the ? operation... `./*[!.test]?.ts`
```js
console.log(entry('./*[!.test]?.ts'))
{
  console: './console.ts',
  core: './core.ts',
  service: './service.ts'
}
```
which also makes no sense, but is oddly the other files i need...

---
so then if i add both... `'./*[!.test]?.ts', './*[!.test].ts'`
```js
console.log(entry('./*[!.test]?.ts', './*[!.test].ts'))
{
  console: './console.ts',
  core: './core.ts',
  service: './service.ts',
  handler: './handler.ts'
}
```
which is exactly what i want...

---
can anyone make any sense of this? i have been racking my brain. i at least have a workaround, but it is driving me a bit crazy not understanding why.

**Comment by thecotne** [comment]
@brewster1134 i am confused do you have `ts` files or `coffee` files?

this test passes for me so i am confused as to what is a problem (i guess it works because of collision in keys of result object which means if files come in different order then result will be different from what i got in my tests)

```js
it('issue #105', () => {
  mockFs({
    'console.ts': '',
    'console.sass': '',
    'console.test.ts': '',
    'core.ts': '',
    'core.test.ts': '',
    'handler.ts': '',
    'package.json': '',
    'README.md': '',
    'service.ts': ''
  })

  var expectedResult = {
    console: './console.ts',
    core: './core.ts',
    handler: './handler.ts',
    service: './service.ts'
  }

  var result = entry(entry.basePath(), './*.ts')

  expect(result).toEqual(expectedResult)
})
```

you can look into docs of node-glob to figure out how to correctly exclude test files https://github.com/isaacs/node-glob#glob-primer

**Comment by brewster1134** [comment]
> @brewster1134 i am confused do you have `ts` files or `coffee` files?

during my experimenting, i was trying all sorts of stuff and my copy/paste to build the pseudo code got screwy, but hopefully the example was still clear ha! **FIXED**

> this test passes for me so i am confused as to what is a problem (i guess it works because of collision in keys of result object which means if files come in different order then result will be different from what i got in my tests)

hmm.. that is an interesting idea, but still doesn't make sense to me. especially since when `handler` is missing, it is right in between `core` and `service`, but then when i combine globs, `handler` is at the bottom vs alphabetically.
what is the `mockFs` function? is that a test suite utility? i wonder how it differs from actually getting info from the file system...

> you can look into docs of node-glob to figure out how to correctly exclude test files https://github.com/isaacs/node-glob#glob-primer

i will check this out and see what i can find

thanks for some other ideas!

**Comment by brewster1134** [comment]
@thecotne i also notice your glob pattern is simply `./*.ts`... so it has to be about the order files are processed. is there anyway to manipulate the order of the files before being processed?  and how does `mockFs` compare to different OSs (i am on osx). i am still not able to achieve the right results, even with playing with the pattern matchers in node-glob.

still dumbfounded...

**Comment by thecotne** [comment]
i don't think [Negative Lookbehind](https://www.regular-expressions.info/lookaround.html#lookbehind) is possible with `node-glob` here is [example](https://gist.github.com/thecotne/73e4537d06b5cdc7e26147b904b9ed98) of how to do this with regex using this pattern `/(?<!\.test)\.ts$/` (matches anything that ends with `.ts` but does not have `.test` before that)

**Comment by thecotne** [comment]
i am closing this since extending node-glob and/or adding other options to achieve behaviour of Negative Lookbehind is out of scope for this package

**Comment by brewster1134** [comment]
since regex is out of the scope of this project, what _would_ be in scope? perhaps sorting options for however a file system returns entries? or chaining glob criteria?  maybe a good place to start would be making `mockFs` behave more accurately to a variety of file systems?

im not sure the inner-workings of this repo, but would be interested in looking at it if anyone had a preferred approach, and where to start looking

**Comment by thecotne** [comment]
this package (which is just [43 lines of code](https://github.com/thecotne/webpack-glob-entry/blob/master/src/index.js)) is my take on [left-pad](https://qz.com/646467/how-one-programmer-broke-the-internet-by-deleting-a-tiny-piece-of-code/) like stupid simple code on npm/github ...

you don't actually need it. you can use [this code](https://gist.github.com/thecotne/73e4537d06b5cdc7e26147b904b9ed98) (which does what you wanted) that i wrote in like 15 minutes or you can write your own function or two to achieve what you need ...

**Comment by brewster1134** [comment]
ha! love the leftpad reference... i was just adding a modified webpack-glob-entry to my bundled dependencies as well... and much appreciation for that 15 minutes... :)

**Comment by brewster1134** [comment]
just fyi... i just ran your same test using a `.js` extension instead of `.ts`, and you will see the same issue i was seeing
