### ISSUE TITLE
Entry is overrided in sub-folders

### ISSUE THREAD

**Issue by lisunovdv** [thecotne/webpack-glob-entry#98]
Folder structure:
./main.js -> main // 1
./util/main.js -> main //2

Result:
`
{
 main: './util/main.js' // 2
}
`

Should be something like this:
`
{
main: 
 main: './main.js ', // 1
 "util/main": './util/main.js' // 2
}
`

**Comment by thecotne** [comment]
default behavior for naming object keys in result is to take file name without extension

if you have multiple entry files with same name in different directories you need to pass function as first parameter that will receive file path and return key

for your use case you can use `entry.basePath` function like so https://runkit.com/embed/krlkiocdphpi
